name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  iconsax: ^0.0.4
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/image_48.png
  - assets/images/image_45.png
  - assets/images/image_46.png
  - assets/images/image_47.png
  - assets/images/image_49.png
  - assets/images/image_43.png
  - assets/vectors/arrow_2_x2.svg
  - assets/vectors/wifi_8_x2.svg
  - assets/vectors/arrow_3_x2.svg
  - assets/vectors/battery_5_x2.svg
  - assets/vectors/ellipse_8841_x2.svg
  - assets/vectors/cellular_connection_7_x2.svg
  - assets/vectors/cellular_connection_1_x2.svg
  - assets/vectors/wifi_1_x2.svg
  - assets/vectors/battery_x2.svg
  - assets/vectors/cellular_connection_4_x2.svg
  - assets/vectors/battery_2_x2.svg
  - assets/vectors/wifi_4_x2.svg
  - assets/vectors/container_10_x2.svg
  - assets/vectors/cellular_connection_10_x2.svg
  - assets/vectors/arrow_1_x2.svg
  - assets/vectors/vector_175_stroke_x2.svg
  - assets/vectors/vector_175_stroke_5_x2.svg
  - assets/vectors/wifi_24_x2.svg
  - assets/vectors/cellular_connection_3_x2.svg
  - assets/vectors/ellipse_6743_x2.svg
  - assets/vectors/wifi_12_x2.svg
  - assets/images/frame_34.png
  - assets/images/frame_33.png
  - assets/images/newspaper_folded_11.png
  - assets/images/frame_35.png
  - assets/vectors/group_2_x2.svg
  - assets/vectors/group_301_x2.svg
  - assets/vectors/cellular_connection_5_x2.svg
  - assets/vectors/wifi_20_x2.svg
  - assets/vectors/menu_icon_1_x2.svg
  - assets/vectors/calendar_5_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/group_334_x2.svg
  - assets/vectors/cellular_connection_28_x2.svg
  - assets/vectors/wifi_3_x2.svg
  - assets/vectors/container_x2.svg
  - assets/vectors/rectangle_15_x2.svg
  - assets/vectors/group_411_x2.svg
  - assets/vectors/caht_4_x2.svg
  - assets/vectors/ellipse_2_x2.svg
  - assets/images/flag_1.png
  - assets/images/hundred_points_1.png
  - assets/images/exclamation_mark_1.png
  - assets/vectors/arrow_8_x2.svg
  - assets/vectors/cellular_connection_21_x2.svg
  - assets/vectors/container_7_x2.svg
  - assets/vectors/wifi_27_x2.svg
  - assets/vectors/ellipse_6741_x2.svg
  - assets/vectors/wifi_9_x2.svg
  - assets/vectors/cellular_connection_x2.svg
  - assets/images/rectangle_8389.png
  - assets/images/rectangle_8383.jpeg
  - assets/images/rectangle_83810.png
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/wifi_6_x2.svg
  - assets/vectors/cellular_connection_24_x2.svg
  - assets/vectors/vector_175_stroke_8_x2.svg
  - assets/vectors/container_4_x2.svg
  - assets/vectors/wifi_14_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/cellular_connection_25_x2.svg
  - assets/vectors/wifi_7_x2.svg
  - assets/vectors/group_30_x2.svg
  - assets/vectors/wifi_16_x2.svg
  - assets/vectors/container_2_x2.svg
  - assets/vectors/cellular_connection_16_x2.svg
  - assets/vectors/cellular_connection_15_x2.svg
  - assets/vectors/vector_175_stroke_9_x2.svg
  - assets/images/rectangle_8385.jpeg
  - assets/images/rectangle_838.png
  - assets/images/rectangle_8382.png
  - assets/images/rectangle_8384.png
  - assets/images/image_43.png
  - assets/images/logo.png
  - assets/images/rectangle_8387.png
  - assets/images/rectangle_83811.jpeg
  - assets/images/rectangle_8388.jpeg
  - assets/images/filter_11.png
  - assets/vectors/group_336_x2.svg
  - assets/vectors/battery_4_x2.svg
  - assets/vectors/vector_175_stroke_6_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/cellular_connection_20_x2.svg
  - assets/vectors/wifi_15_x2.svg
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/images/image_48.png
  - assets/images/image_49.png
  - assets/images/image_45.png
  - assets/images/image_46.png
  - assets/images/image_43.png
  - assets/images/image_47.png
  - assets/vectors/battery_1_x2.svg
  - assets/vectors/cellular_connection_12_x2.svg
  - assets/vectors/wifi_21_x2.svg
  - assets/vectors/arrow_5_x2.svg
  - assets/vectors/arrow_4_x2.svg
  - assets/vectors/ellipse_884_x2.svg
  - assets/images/afbea_4990382432.png
  - assets/images/logo.png
  - assets/vectors/vector_25241_x2.svg
  - assets/vectors/wifi_11_x2.svg
  - assets/vectors/cellular_connection_26_x2.svg
  - assets/vectors/ellipse_1_x2.svg
  - assets/vectors/battery_6_x2.svg
  - assets/images/logo.png
  - assets/images/newspaper_folded_11.png
  - assets/vectors/calendar_7_x2.svg
  - assets/vectors/caht_2_x2.svg
  - assets/vectors/group_333_x2.svg
  - assets/vectors/ellipse_6742_x2.svg
  - assets/vectors/cellular_connection_13_x2.svg
  - assets/vectors/location_6_x2.svg
  - assets/vectors/container_9_x2.svg
  - assets/vectors/group_414_x2.svg
  - assets/vectors/location_7_x2.svg
  - assets/vectors/arrow_6_x2.svg
  - assets/vectors/cellular_connection_9_x2.svg
  - assets/vectors/location_5_x2.svg
  - assets/vectors/vector_175_stroke_7_x2.svg
  - assets/vectors/calendar_1_x2.svg
  - assets/vectors/calendar_3_x2.svg
  - assets/vectors/vector_175_stroke_2_x2.svg
  - assets/vectors/calendar_2_x2.svg
  - assets/vectors/rectangle_153_x2.svg
  - assets/vectors/wifi_22_x2.svg
  - assets/vectors/wifi_25_x2.svg
  - assets/vectors/icon_area_x2.svg
  - assets/vectors/wifi_18_x2.svg
  - assets/vectors/group_1_x2.svg
  - assets/vectors/wifi_2_x2.svg
  - assets/vectors/cellular_connection_2_x2.svg
  - assets/vectors/group_140_x2.svg
  - assets/vectors/cellular_connection_11_x2.svg
  - assets/vectors/group_x2.svg
  - assets/vectors/container_8_x2.svg
  - assets/vectors/vector_175_stroke_4_x2.svg
  - assets/images/image_53.png
  - assets/images/image_54.png
  - assets/images/image_52.png
  - assets/images/dots_4.png
  - assets/images/newspaper_folded_1.png
  - assets/images/image_431.png
  - assets/images/image_521.png
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/wifi_28_x2.svg
  - assets/vectors/calendar_13_x2.svg
  - assets/vectors/material_symbolsarrow_outward_x2.svg
  - assets/vectors/group_41_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/cellular_connection_17_x2.svg
  - assets/vectors/group_331_x2.svg
  - assets/vectors/caht_x2.svg
  - assets/vectors/material_symbolsarrow_outward_1_x2.svg
  - assets/vectors/battery_7_x2.svg
  - assets/vectors/rectangle_151_x2.svg
  - assets/images/newspaper_folded_11.png
  - assets/vectors/group_332_x2.svg
  - assets/vectors/wifi_x2.svg
  - assets/vectors/calendar_4_x2.svg
  - assets/vectors/arrow_x2.svg
  - assets/vectors/location_2_x2.svg
  - assets/vectors/group_413_x2.svg
  - assets/vectors/rectangle_154_x2.svg
  - assets/vectors/calendar_11_x2.svg
  - assets/vectors/cellular_connection_18_x2.svg
  - assets/vectors/location_4_x2.svg
  - assets/vectors/location_3_x2.svg
  - assets/vectors/calendar_9_x2.svg
  - assets/vectors/cellular_connection_19_x2.svg
  - assets/vectors/location_1_x2.svg
  - assets/vectors/caht_3_x2.svg
  - assets/vectors/calendar_10_x2.svg
  - assets/vectors/wifi_17_x2.svg
  - assets/vectors/calendar_x2.svg
  - assets/vectors/location_8_x2.svg
  - assets/vectors/vector_175_stroke_10_x2.svg
  - assets/vectors/ellipse_674_x2.svg
  - assets/vectors/calendar_6_x2.svg
  - assets/vectors/calendar_12_x2.svg
  - assets/vectors/container_6_x2.svg
  - assets/vectors/location_x2.svg
  - assets/images/ellipse_23.png
  - assets/images/image_44.png
  - assets/images/ellipse_21.png
  - assets/images/image_43.png
  - assets/images/ellipse_25.png
  - assets/images/newspaper_folded_11.png
  - assets/vectors/menu_icon_x2.svg
  - assets/vectors/calendar_8_x2.svg
  - assets/vectors/rectangle_152_x2.svg
  - assets/vectors/container_3_x2.svg
  - assets/vectors/group_302_x2.svg
  - assets/vectors/location_9_x2.svg
  - assets/vectors/rectangle_8151_x2.svg
  - assets/vectors/group_335_x2.svg
  - assets/vectors/location_10_x2.svg
  - assets/vectors/caht_1_x2.svg
  - assets/vectors/cellular_connection_22_x2.svg
  - assets/vectors/wifi_26_x2.svg
  - assets/vectors/container_11_x2.svg
  - assets/vectors/ellipse_252_x2.svg
  - assets/vectors/rectangle_815_x2.svg
  - assets/vectors/ellipse_271_x2.svg
  - assets/vectors/ellipse_251_x2.svg
  - assets/vectors/star_61_x2.svg
  - assets/vectors/star_6_x2.svg
  - assets/vectors/container_5_x2.svg
  - assets/vectors/vector_2524_x2.svg
  - assets/vectors/group_412_x2.svg
  - assets/vectors/ellipse_27_x2.svg
  - assets/vectors/cellular_connection_23_x2.svg
  - assets/vectors/wifi_13_x2.svg
  - assets/images/rectangle_8383.jpeg
  - assets/images/rectangle_8389.png
  - assets/vectors/cellular_connection_27_x2.svg
  - assets/vectors/cellular_connection_8_x2.svg
  - assets/vectors/container_1_x2.svg
  - assets/vectors/wifi_10_x2.svg
  - assets/vectors/vector_175_stroke_3_x2.svg
  - assets/vectors/wifi_23_x2.svg
  - assets/images/rectangle_8384.png
  - assets/images/image_43.png
  - assets/images/rectangle_8388.jpeg
  - assets/images/rectangle_8382.png
  - assets/images/rectangle_8385.jpeg
  - assets/images/rectangle_83811.jpeg
  - assets/images/rectangle_838.png
  - assets/images/rectangle_8383.jpeg
  - assets/images/rectangle_8387.png
  - assets/images/rectangle_8386.png
  - assets/images/rectangle_8381.png
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/cellular_connection_14_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/battery_3_x2.svg
  - assets/vectors/wifi_19_x2.svg
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/group_33_x2.svg
  - assets/vectors/vector_175_stroke_1_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/images/image_43.png
  - assets/images/image_431.png
  - assets/vectors/battery_8_x2.svg
  - assets/vectors/wifi_5_x2.svg
  - assets/vectors/arrow_7_x2.svg
  - assets/vectors/cellular_connection_6_x2.svg

